import { NewsInterface } from './newsInterface';

export const newsApi : NewsInterface[] = [{
    tema: 'argentina',
    imagen: 'https://picsum.photos/250/100?random=1',
    article: 'El día que volvió a flamear la bandera Argentina en las Islas Malvinas',
    descripcion: 'Claudia Camargo es una atleta de alto rendimiento de Paraná que nos cuenta el día que decidió correr en Malvinas un maratón y lo ganó. Los detalles de su preparación y lo que sintió al ganar una competencia tan especial.',   
    cssContenidoNews: 'newsArg',
    cssImagen: 'imagenArg',
    cssArticle: 'articleArg',
    cssDescripcion: 'descripcionArg',
    cssBtnLike: 'btnLikeArg',
    cssBtnShare: 'btnShareArg',
   },
   {
     tema: 'argentina',
     imagen: 'https://picsum.photos/250/100?random=1',
     article: 'La bandera para todo y para todos',
     descripcion: 'Hace diez días, cuando el seleccionado nacional de fútbol se consagró campeón mundial en México, nuestra ciudad festejó el triunfo como pocas veces se había visto. Comentario al margen del espectáculo imponente que dio la gente, se dice que fue tan grande el número de banderas que se vio que "Buenos Aires nunca se vistió de celeste y blanco como ese día".',
     cssContenidoNews: 'newsArg',
     cssImagen: 'imagenArg',
     cssArticle: 'articleArg',
     cssDescripcion: 'descripcionArg',
     cssBtnLike: 'btnLikeArg',
     cssBtnShare: 'btnShareArg',
    },
   {
     tema: 'argentina',
     imagen: 'https://picsum.photos/250/100?random=1',
     article: 'La bandera para todo y para todos',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsArg',
     cssImagen: 'imagenArg',
     cssArticle: 'articleArg',
     cssDescripcion: 'descripcionArg',
     cssBtnLike: 'btnLikeArg',
     cssBtnShare: 'btnShareArg',
    },
   {
     tema: 'argentina',
     imagen: 'https://picsum.photos/250/100?random=1',
     article: 'La bandera para todo y para todos',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsArg',
     cssImagen: 'imagenArg',
     cssArticle: 'articleArg',
     cssDescripcion: 'descripcionArg',
     cssBtnLike: 'btnLikeArg',
     cssBtnShare: 'btnShareArg',
    },
    {
     tema: 'profecional',
     imagen: 'https://picsum.photos/100/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor Lorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorLorem ipsum dolorsit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsProf',
     cssImagen: 'imagenProf',
     cssArticle: 'articleProf',
     cssDescripcion: 'descripcionProf',
     cssBtnLike: 'btnLikeProf',
     cssBtnShare: 'btnShareProf',
    },
    {
     tema: 'profecional',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsProf',
     cssImagen: 'imagenProf',
     cssArticle: 'articleProf',
     cssDescripcion: 'descripcionProf',
     cssBtnLike: 'btnLikeProf',
     cssBtnShare: 'btnShareProf',
    },
    {
     tema: 'profecional',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsProf',
     cssImagen: 'imagenProf',
     cssArticle: 'articleProf',
     cssDescripcion: 'descripcionProf',
     cssBtnLike: 'btnLikeProf',
     cssBtnShare: 'btnShareProf',
    },
    {
     tema: 'naif',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsNaif',
     cssImagen: 'imagenNaif',
     cssArticle: 'articleNaif',
     cssDescripcion: 'descripcionNaif',
     cssBtnLike: 'btnLikeNaif',
     cssBtnShare: 'btnShareNaif',
    },
    {
     tema: 'naif',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsNaif',
     cssImagen: 'imagenNaif',
     cssArticle: 'articleNaif',
     cssDescripcion: 'descripcionNaif',
     cssBtnLike: 'btnLikeNaif',
     cssBtnShare: 'btnShareNaif',
    },
    {
     tema: 'naif',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsNaif',
     cssImagen: 'imagenNaif',
     cssArticle: 'articleNaif',
     cssDescripcion: 'descripcionNaif',
     cssBtnLike: 'btnLikeNaif',
     cssBtnShare: 'btnShareNaif',
    },
    {
     tema: 'custom',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsCust',
     cssImagen: 'imagenCust',
     cssArticle: 'articleCust',
     cssDescripcion: 'descripcionCust',
     cssBtnLike: 'btnLikeCust',
     cssBtnShare: 'btnShareCust',
    },
    {
     tema: 'custom',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsCust',
     cssImagen: 'imagenCust',
     cssArticle: 'articleCust',
     cssDescripcion: 'descripcionCust',
     cssBtnLike: 'btnLikeCust',
     cssBtnShare: 'btnShareCust',
    },
    {
     tema: 'custom',
     imagen: 'https://picsum.photos/150/300?random=1',
     article: 'Titulo',
     descripcion: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus voluptatibus eligendi consequuntur laudantium dignissimos nam cupiditate voluptatum, iste soluta! Minus maiores nesciunt, nihil debitis facilis nemo quam minima libero? Quam?',
     cssContenidoNews: 'newsCust',
     cssImagen: 'imagenCust',
     cssArticle: 'articleCust',
     cssDescripcion: 'descripcionCust',
     cssBtnLike: 'btnLikeCust',
     cssBtnShare: 'btnShareCust',
    }];